"""update_user_preferences_to_clerk

Revision ID: 10a49d43985d
Revises: e6236358d3ac
Create Date: 2026-07-09 21:10:30.058226
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '10a49d43985d'
down_revision = 'e6236358d3ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_user_preferences_user_id', table_name='user_preferences')
    op.create_index(op.f('ix_user_preferences_clerk_user_id'), 'user_preferences', ['clerk_user_id'], unique=True)
    op.drop_constraint('user_preferences_user_id_fkey', 'user_preferences', type_='foreignkey')
    op.drop_column('user_preferences', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_preferences_user_id_fkey', 'user_preferences', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_preferences_clerk_user_id'), table_name='user_preferences')
    op.create_index('ix_user_preferences_user_id', 'user_preferences', ['user_id'], unique=True)
    op.drop_column('user_preferences', 'clerk_user_id')
    # ### end Alembic commands ###
