"""Add StudyAnnotation

Revision ID: 8f03cef40015
Revises: d4a688b06ebc
Create Date: 2026-05-26 17:13:33.135381
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8f03cef40015'
down_revision = 'd4a688b06ebc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_annotations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('underline_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_annotations_document_id'), 'study_annotations', ['document_id'], unique=False)
    op.create_index(op.f('ix_study_annotations_id'), 'study_annotations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_annotations_id'), table_name='study_annotations')
    op.drop_index(op.f('ix_study_annotations_document_id'), table_name='study_annotations')
    op.drop_table('study_annotations')
    # ### end Alembic commands ###
