"""Add RelatedVideo

Revision ID: a6eef9f78ea8
Revises: 20260518_0002
Create Date: 2026-05-25 18:04:12.348382
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a6eef9f78ea8'
down_revision = '20260518_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_videos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relevance_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_related_videos_document_id'), 'related_videos', ['document_id'], unique=False)
    op.create_index(op.f('ix_related_videos_id'), 'related_videos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_related_videos_id'), table_name='related_videos')
    op.drop_index(op.f('ix_related_videos_document_id'), table_name='related_videos')
    op.drop_table('related_videos')
    # ### end Alembic commands ###
