"""add_srs_fields_to_flashcards

Revision ID: b57e556e02c0
Revises: 20260614_0001
Create Date: 2026-07-08 19:22:37.832400
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57e556e02c0'
down_revision = '20260614_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('next_review_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('flashcards', sa.Column('interval', sa.Integer(), server_default='0', nullable=False))
    op.add_column('flashcards', sa.Column('repetition', sa.Integer(), server_default='0', nullable=False))
    op.add_column('flashcards', sa.Column('easiness_factor', sa.Float(), server_default='2.5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'easiness_factor')
    op.drop_column('flashcards', 'repetition')
    op.drop_column('flashcards', 'interval')
    op.drop_column('flashcards', 'next_review_date')
    # ### end Alembic commands ###
