"""Add clerk_user_id to Document

Revision ID: d4a688b06ebc
Revises: dd335b7f14f7
Create Date: 2026-05-26 12:50:37.623796
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd4a688b06ebc'
down_revision = 'dd335b7f14f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_documents_clerk_user_id'), 'documents', ['clerk_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_clerk_user_id'), table_name='documents')
    op.drop_column('documents', 'clerk_user_id')
    # ### end Alembic commands ###
