"""add published_at to related_videos

Revision ID: dd335b7f14f7
Revises: 20260526_0001
Create Date: 2026-05-26 10:31:43.952812
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd335b7f14f7'
down_revision = '20260526_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
